language: node_js
node_js:
   - "9"

branches:
   only:
      - /.*/

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

deploy:
   provider: firebase
   token:
      secure: $FIREBASE_TOKEN
   on:
      branch: master