language: node_js
node_js:
   - "9"

branches:
   only:
      - /.*/

before_install:
   - npm install -g greenkeeper-lockfile@1

before_script:
   - npm install -g @angular/cli
   - greenkeeper-lockfile-update

script:
   - ng build --prod --aot

after_script:
   - greenkeeper-lockfile-upload

deploy:
   provider: firebase
   token:
      secure: $FIREBASE_TOKEN
   on:
      branch: master