language: node_js
node_js:
   - "9"

branches:
   only:
      - master
      - /^greenkeeper/.*$/

before_script:
   - npm install -g @angular/cli
   - npm install -g firebase-tools

script:
   - ng build --prod --aot

after_success:
   - firebase deploy --token $FIREBASE_TOKEN