language: node_js
node_js:
- '10'
branches:
  only:
  - /.*/
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm install
- greenkeeper-lockfile-update
script:
- ng build --prod --aot
after_script:
- greenkeeper-lockfile-upload
deploy:
  provider: firebase
  token:
    secure: "MQxn0QlLSujclU3ugqI1cCVPgjpwb8sd7a+LV5gT2/JzHM7HzK1Z/zIefV/yFJ6dx71XCiWkzuf60htFlz3cm8GIYm6IkFj05g6aHeUKufr1kcUvS4i1YDK6zm6opqcQdnli5P3fCvFvgAtVXbjwK2AC4dv0xtqDTsFWcqm0tF6/fv+eqseCXkfBeANmxhrweyQKLd72JEaZ8Qyx2SDBhaApEWP9kSFUJNrEcBAgFC2oO+CWpmeJ/rjOzFCbrzkCOOVQW3mwWmUUc02b1SU19wXKwQfWK4/XpE5k5VF/gF+3CeTzuPTOxweTJaJ+PWwOpq36/uiFQVfoC1dLhFIqxtxTpsFwxrnyaR3CCSkEDcJuWKhXjSS+oVD2ncrM+TmF7GsEK1sBOk62VKuEY+yWLYWIieKdIKOpGbI59FHQtqD3ZbwQHUJhtaOsmG/777a5bHVwiTdLBoJKo3qN6OfmUFH6mE6NV6eJ64KM4vNK9hFOor6ZmKze/DqBJ9hIOlS4Z+pALpszZ6pZy2Xz81Yh0RFJHJnZbV9AR0Dmw5wQEPPrEXhfgqAd8Ib0XKLizBR3MPTJoER9LPJQUi+uvs4zPhrL3TKHLFShQ2BJw+J8XYE++iv/mwBbhYhFChlGq15QO3Q3M1HAvSPHe7l84entfa+BKar1Uqb+DY+Uod63hRE="
  on:
    branch: master
  skip_cleanup: true
