language: node_js
node_js:
- '9'
branches:
  only:
  - /.*/
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm install -g @angular/cli
- greenkeeper-lockfile-update
script:
- ng build --prod --aot
after_script:
- greenkeeper-lockfile-upload
deploy:
  provider: firebase
  token:
    secure: "wd82J+npr9ba+R2Jj9e0wAB1QKq1FoCTkQhQkoEfQBdZMY7AMuNqRNZSrPaRglLFYeMqqxW/qDW5kar7N3AdvYBaK/qiaUHuJykHxbAQE2dlzLsO8+BwVctCD8uRT7OEO9TUnKv0iTSq3lLWrQpKt7X5KFuPeI6znw27V8+meQfxxtX8QY+F4q9hpqC3FXOC0gPd8n9S/1sO4cb6JrEi9Mq0eKmUgu0tSCejhC7a3RcIVRGqZHXU9URmuRsfImMwr6EhsuNkjDMsPc387sRcOAsLAYaBvALeTCClgotkeShgJN14ZvqI3aw6SA2kIHT28bLiINnw9ty7rROTqpWvOMRUFXqQM0efdsebJ2TJwxdOu9W8U/sfQqDO/JaTeBiDxWVBri6f/xljdAG5WOjIf/o6SY+Rpb4jAZJNXjooMZPGa/nqLf07LlHQe62EN0y50y6BMNiZdQ0jiwM2WasaK+uNKS6CY+KgWwdaJBbt+7g0A0uYc4cWBCHLTX00OZ2SVsOAy3OnPq1pG/AES4QP7uipa67Xy7UrwcMg2Tj7i7rmEGOIsUr3VNW8XYilK0AipLad8Tk7jZMfaAh3//5xtSW7Akj7CrMK9MKhJHfflX4VLFTLEtlmu1gT0QgCNtIcr3pOKCqJnh4rHNkkRPg6Tr2X6SkbaWca5BNBPGcvy1g="
  on:
    branch: master
  skip_cleanup: true
